package com.ablehealth.measures.hedis.year2019;

import com.ablehealth.model.*
import com.ablehealth.payloads.*;
import com.ablehealth.results.*;

global PatientResults controlSet;

rule 'Year2019.Cis4.Success.performance_met'
when
    PatientDenominator($program: program, $patient: patient, measure == 'Year2019.Cis4')
    HedisYear2019Cis4SuccessPerformanceMet()
then
    controlSet.addPatientMeasureStatus($program, $patient, 'Year2019.Cis4', MeasureStatusValue.SUCCESS, "performance_met");
end

rule 'Year2019.Cis4.Gap.performance_not_met'
when
    PatientDenominator($program: program, $patient: patient, measure == 'Year2019.Cis4')
then
    controlSet.addPatientMeasureStatus($program, $patient, 'Year2019.Cis4', MeasureStatusValue.GAP, "performance_not_met");
end

