package com.ablehealth;

import com.ablehealth.model.*
import com.ablehealth.payloads.*;
import com.ablehealth.results.*;

global PatientResults controlSet;

rule 'Year2019.Coa1.Success.performance_met'
when
    PatientDenominator($program: program, $patient: patient, measure == 'Year2019.Coa1')
    exists ClinicalActivity(
      startsDuring($program.measurementPeriod),
      withValueSet("HedisYear2019", "ADVANCE_CARE_PLANNING") ||
      withValueSet("AbleYear2016", "ADVANCE_DIRECTIVE") ||
      withValueSet("AbleYear2016", "ADVANCE_DIRECTIVE_DISCUSSED")
    )
then
    controlSet.addPatientMeasureStatus($program, $patient, 'Year2019.Coa1', MeasureStatusValue.SUCCESS, "performance_met");
end

rule 'Year2019.Coa1.Gap.performance_not_met'
when
    PatientDenominator($program: program, $patient: patient, measure == 'Year2019.Coa1')
then
    controlSet.addPatientMeasureStatus($program, $patient, 'Year2019.Coa1', MeasureStatusValue.GAP, "performance_not_met");
end
