package com.ablehealth;

import com.ablehealth.model.*
import com.ablehealth.payloads.*;
import com.ablehealth.results.*;

global PatientResults controlSet;

rule 'Year2019.Coa3.Success.performance_met'
when
    PatientDenominator($program: program,  $patient: patient, measure == 'Year2019.Coa3')
    exists ClinicalActivity(
        startsDuring($program.measurementPeriod),
        withValueSet("HedisYear2019", "FUNCTIONAL_STATUS_ASSESSMENT") ||
        withValueSet("AbleYear2019", "FUNCTIONAL_STATUS_ASSESSMENT")
    )

then
    controlSet.addPatientMeasureStatus($program, $patient, 'Year2019.Coa3', MeasureStatusValue.SUCCESS, "performance_met");
end

rule 'Year2019.Coa3.Gap.performance_not_met'
when
    PatientDenominator($program: program, $patient: patient, measure == 'Year2019.Coa3')
then
    controlSet.addPatientMeasureStatus($program, $patient, 'Year2019.Coa3', MeasureStatusValue.GAP, "performance_not_met");
end
