package com.ablehealth;

import com.ablehealth.model.*
import com.ablehealth.payloads.*;
import com.ablehealth.results.*;

global PatientResults controlSet;

rule 'Year2019.Coa4.Success.performance_met'
when
    PatientDenominator($program: program, $patient: patient, measure == 'Year2019.Coa4')
    exists ClinicalActivity(
        startsDuring($program.measurementPeriod),
        withValueSet("HedisYear2019", "PAIN_ASSESSMENT") ||
        withValueSet("AbleYear2019", "PAIN_ASSESSMENTS") ||
        withValueSet("AbleYear2019", "STANDARDIZED_PAIN_ASSESSMENT_TOOL") ||
        withValueSet("MipsYear2019", "PERFORMANCE_MET_G8730") ||
        withValueSet("MipsYear2019", "PERFORMANCE_MET_G8731")
    )
then
    controlSet.addPatientMeasureStatus($program, $patient, 'Year2019.Coa4', MeasureStatusValue.SUCCESS, "performance_met");
end

rule 'Year2019.Coa4.Gap.performance_not_met'
when
    PatientDenominator($program: program, $patient: patient, measure == 'Year2019.Coa4')
then
    controlSet.addPatientMeasureStatus($program, $patient, 'Year2019.Coa4', MeasureStatusValue.GAP, "performance_not_met");
end
