package com.ablehealth;

import com.ablehealth.model.*
import com.ablehealth.payloads.*;
import com.ablehealth.results.*;

global PatientResults controlSet;

rule 'Year2019.Ima1.Success.performance_met'
when
	PatientDenominator($program: program, $patient: patient, measure == 'Year2019.Ima1')
	(
		HedisImaYear2019SuccessMeningococcal()
	)
then
	controlSet.addPatientMeasureStatus($program, $patient, 'Year2019.Ima1', MeasureStatusValue.SUCCESS, "performance_met");
end