package com.ablehealth;

import com.ablehealth.model.*
import com.ablehealth.payloads.*;
import com.ablehealth.results.*;

global PatientResults controlSet;

rule 'Year2019.Ima3.Success.performance_met'
when
	PatientDenominator($program: program, $patient: patient, measure == 'Year2019.Ima3')
	HedisImaYear2019SuccessHpvVaccine()
then
	controlSet.addPatientMeasureStatus($program, $patient, 'Year2019.Ima3', MeasureStatusValue.SUCCESS, "performance_met");
end