package com.ablehealth;

import com.ablehealth.model.*
import com.ablehealth.payloads.*;
import com.ablehealth.results.*;

global PatientResults controlSet;

rule 'Year2019.Ima4.Success.performance_met'
when
	PatientDenominator($program: program, $patient: patient, measure == 'Year2019.Ima4')
	( 
		HedisImaYear2019SuccessMeningococcal()
	)
	and
	( 
		HedisImaYear2019SuccessTdapVaccine()
	)
then
	controlSet.addPatientMeasureStatus($program, $patient, 'Year2019.Ima4', MeasureStatusValue.SUCCESS, "performance_met");
end