package com.ablehealth;

import com.ablehealth.model.*
import com.ablehealth.payloads.*;
import com.ablehealth.results.*;

global PatientResults controlSet;

rule 'Year2019.Hedis.UopRate3.SuccessReasons.PerformanceMet'
when
    PatientDenominator($program: program, $patient: patient, measure == 'Year2019.UopRate3')
    Year2019UopFourProviders()
    Year2019UopFourPharmacyNpis()
then
    controlSet.addPatientMeasureStatus($program, $patient, 'Year2019.UopRate3', MeasureStatusValue.SUCCESS, 'performance_met');
end

rule 'Year2019.Hedis.UopRate3.GapReasons.PerformanceNotMet'
when
    PatientDenominator($program: program, $patient: patient, measure == 'Year2019.UopRate3')
then
    controlSet.addPatientMeasureStatus($program, $patient, 'Year2019.UopRate3', MeasureStatusValue.GAP, 'performance_not_met');
end
