package com.ablehealth;

import com.ablehealth.model.*
import com.ablehealth.payloads.*;
import com.ablehealth.results.*;

global PatientResults controlSet;

rule 'Year2019.Able.Awv2.Denominator'
when
    $program: Program(rules contains 'measure.Able.2019.Awv2')
    $patient: Patient()
then
    insert(new PatientDenominator($program, $patient, 'Year2019.Awv2'));
end

rule 'Year2019.Able.Awv2.SuccessReasons.PerformanceMet'
when
    PatientDenominator($program: program, $patient: patient, measure == 'Year2019.Awv2')
    exists ClinicalActivity(
        startsDuring($program.measurementPeriod),
        withValueSet("AbleYear2019", "ANNUAL_WELLNESS_VISIT___COMMERCIAL_MEDICAID")
    )
then
    controlSet.addPatientMeasureStatus($program, $patient, 'Year2019.Awv2', MeasureStatusValue.SUCCESS, 'performance_met');
end

rule 'Year2019.Able.Awv2.GapReasons.PerformanceNotMet'
when
    PatientDenominator($program: program, $patient: patient, measure == 'Year2019.Awv2')
then
    controlSet.addPatientMeasureStatus($program, $patient, 'Year2019.Awv2', MeasureStatusValue.GAP, 'performance_not_met');
end
