package com.ablehealth;

import com.ablehealth.model.*
import com.ablehealth.payloads.*;
import com.ablehealth.results.*;

global PatientResults controlSet;

rule 'Year2019.Mips134.Denominator'
when
	$program: Program(rules contains 'measure.Mips.2019.Mips134')
	$mips134encounter: ClinicalActivity(
		startsDuring($program.measurementPeriod),
		withValueSet("MipsYear2019", "MIPS_134_ENCOUNTER")
	)
	Patient(
		getAgeInYearsAt($program.measurementPeriod.start.minusDays(1)) >= 12
	)
then
	insert(new EncounterDenominator($program, $mips134encounter, 'Year2019.Mips134'));
end

rule 'Year2019.Mips134.Exclusion.exclusion_1'
when
	EncounterDenominator($program: program, $encounter: clinicalActivity, measure == 'Year2019.Mips134')
	$patient: Patient()
	(
		exists (
			Diagnosis(
				startsBefore($encounter.startDate),
				overlaps($encounter),
				withValueSet("VsacYear2019", "BIPOLAR_DISORDER") ||
				withValueSet("VsacYear2019", "DEPRESSION_DIAGNOSIS")
			)
		)
		or exists(
			ClinicalActivity(
				startsDuring($encounter),
				withValueSet("MipsYear2019", "DENOMINATOR_EXCLUSION_G9717")
			)
		)
	)
then
	controlSet.addPatientMeasureStatus($program, $patient, 'Year2019.Mips134', MeasureStatusValue.EXCLUSION, "exclusion_1");
	controlSet.addProviderPatientMeasureStatus($program, $patient, $encounter.providerExternalId,'Year2019.Mips134', MeasureStatusValue.EXCLUSION, "exclusion_1");
end

rule 'Year2019.Mips134.Success.G8431'
when
	EncounterDenominator($program: program, $encounter: clinicalActivity, measure == 'Year2019.Mips134')
	$patient: Patient()
	(
		exists(
			ClinicalActivity(
				startsDuring($encounter),
				withValueSet("MipsYear2019", "PERFORMANCE_MET_G8431")
			)
		)
		or exists (
			(
				exists (
					Patient(
						$patient.getAgeInYearsAt($program.measurementPeriod.start) <= 17
					)
					and exists (
						ClinicalActivity(
							startsDuring($encounter),
							result == 'positive',
							$patient.getAgeInYearsAt($program.measurementPeriod.start) <= 17,
							withValueSet("VsacYear2019", "ADOLESCENT_DEPRESSION_SCREENING")
						)
					)
				)
				or exists (
					ClinicalActivity(
						startsDuring($encounter),
						resultAsDecimal >= 5,
						withValueSet("VsacYear2019", "PHQ_9_TOOL")
					)
				)
			)
			and (
				Patient(
					$patient.getAgeInYearsAt($program.measurementPeriod.start) <= 17
				)
				and (
					exists (
						ClinicalActivity(
							startsDuring($encounter),
							withValueSet("VsacYear2019", "FOLLOW_UP_FOR_DEPRESSION___ADOLESCENT") ||
							withValueSet("VsacYear2019", "ADDITIONAL_EVALUATION_FOR_DEPRESSION___ADOLESCENT") ||
							withValueSet("VsacYear2019", "REFERRAL_FOR_DEPRESSION_ADOLESCENT") ||
							withValueSet("VsacYear2019", "SUICIDE_RISK_ASSESSMENT")
						)
					)
					or exists (
						Medication(
							overlaps($encounter),
							withValueSet("VsacYear2019", "DEPRESSION_MEDICATIONS___ADOLESCENT")
						)
					)
				)
			)
		)
		or exists (
			(
				(
					Patient(
						$patient.getAgeInYearsAt($program.measurementPeriod.start) >= 18
					)
					and exists (
						ClinicalActivity(
							startsDuring($encounter),
							result == 'positive',
							withValueSet("VsacYear2019", "ADULT_DEPRESSION_SCREENING")
						)
					)
				)
				or exists (
					ClinicalActivity(
						startsDuring($encounter),
						resultAsDecimal >= 5,
						withValueSet("VsacYear2019", "PHQ_9_TOOL")
					)
				)
			)
			and (
				Patient(
					$patient.getAgeInYearsAt($program.measurementPeriod.start) >= 18
				)
				and (
					exists (
						ClinicalActivity(
							startsDuring($encounter),
							withValueSet("VsacYear2019", "FOLLOW_UP_FOR_DEPRESSION___ADULT") ||
							withValueSet("VsacYear2019", "ADDITIONAL_EVALUATION_FOR_DEPRESSION___ADULT") ||
							withValueSet("VsacYear2019", "REFERRAL_FOR_DEPRESSION_ADULT") ||
							withValueSet("VsacYear2019", "SUICIDE_RISK_ASSESSMENT")
						)
					)
					or exists (
						Medication(
							overlaps($encounter),
							withValueSet("VsacYear2019", "DEPRESSION_MEDICATIONS___ADULT")
						)
					)
				)
			)
		)
	)
then
	controlSet.addPatientMeasureStatus($program, $patient, 'Year2019.Mips134', MeasureStatusValue.SUCCESS, "G8431");
	controlSet.addProviderPatientMeasureStatus($program, $patient, $encounter.providerExternalId,'Year2019.Mips134', MeasureStatusValue.SUCCESS, "G8431");
end

rule 'Year2019.Mips134.Success.G8510'
when
	EncounterDenominator($program: program, $encounter: clinicalActivity, measure == 'Year2019.Mips134')
	$patient: Patient()
	(
		exists(
			ClinicalActivity(
				startsDuring($encounter),
				withValueSet("MipsYear2019", "PERFORMANCE_MET_G8510")
			)
		)
		or (
			Patient(
				$patient.getAgeInYearsAt($program.measurementPeriod.start) <= 17
			)
			and exists (
				ClinicalActivity(
					startsDuring($encounter),
					result == 'negative',
					withValueSet("VsacYear2019", "ADOLESCENT_DEPRESSION_SCREENING")
				)
			)
		)
		or (
			Patient(
				$patient.getAgeInYearsAt($program.measurementPeriod.start) >= 18
			)
			and exists (
				ClinicalActivity(
					startsDuring($encounter),
					result == 'negative',
					withValueSet("VsacYear2019", "ADULT_DEPRESSION_SCREENING")
				)
			)
		)
		or exists (
			ClinicalActivity(
				startsDuring($encounter),
				resultAsDecimal < 5,
				withValueSet("VsacYear2019", "PHQ_9_TOOL")
			)
		)
	)
then
	controlSet.addPatientMeasureStatus($program, $patient, 'Year2019.Mips134', MeasureStatusValue.SUCCESS, "G8510");
	controlSet.addProviderPatientMeasureStatus($program, $patient, $encounter.providerExternalId,'Year2019.Mips134', MeasureStatusValue.SUCCESS, "G8510");
end

rule 'Year2019.Mips134.Exception.G8433'
when
	EncounterDenominator($program: program, $encounter: clinicalActivity, measure == 'Year2019.Mips134')
	$patient: Patient()
	(
		exists(
			ClinicalActivity(
				startsDuring($encounter),
				withValueSet("MipsYear2019", "DENOMINATOR_EXCEPTION_G8433")
			)
		)
	)
then
	controlSet.addPatientMeasureStatus($program, $patient, 'Year2019.Mips134', MeasureStatusValue.EXCEPTION, "G8433");
	controlSet.addProviderPatientMeasureStatus($program, $patient, $encounter.providerExternalId,'Year2019.Mips134', MeasureStatusValue.EXCEPTION, "G8433");
end

rule 'Year2019.Mips134.Gap.G8511'
when
	EncounterDenominator($program: program, $encounter: clinicalActivity, measure == 'Year2019.Mips134')
	$patient: Patient()
	(
		exists(
			ClinicalActivity(
				startsDuring($encounter),
				withValueSet("MipsYear2019", "PERFORMANCE_NOT_MET_G8511")
			)
		)
		or (
			Patient(
				$patient.getAgeInYearsAt($program.measurementPeriod.start) <= 17
			)
			and exists (
				ClinicalActivity(
					startsDuring($encounter),
					result == 'positive',
					withValueSet("VsacYear2019", "ADOLESCENT_DEPRESSION_SCREENING")
				)
			)
		)
		or (
			Patient(
				$patient.getAgeInYearsAt($program.measurementPeriod.start) >= 18
			)
			and exists (
				ClinicalActivity(
					startsDuring($encounter),
					result == 'positive',
					withValueSet("VsacYear2019", "ADULT_DEPRESSION_SCREENING")
				)
			)
		)
		or exists (
			ClinicalActivity(
				startsDuring($encounter),
				resultAsDecimal >= 5,
				withValueSet("VsacYear2019", "PHQ_9_TOOL")
			)
		)
	)
then
	controlSet.addPatientMeasureStatus($program, $patient, 'Year2019.Mips134', MeasureStatusValue.GAP, "G8511");
	controlSet.addProviderPatientMeasureStatus($program, $patient, $encounter.providerExternalId,'Year2019.Mips134', MeasureStatusValue.GAP, "G8511");
end

rule 'Year2019.Mips134.Gap.G8432'
when
	EncounterDenominator($program: program, $encounter: clinicalActivity, measure == 'Year2019.Mips134')
	$patient: Patient()
then
	controlSet.addPatientMeasureStatus($program, $patient, 'Year2019.Mips134', MeasureStatusValue.GAP, "G8432");
	controlSet.addProviderPatientMeasureStatus($program, $patient, $encounter.providerExternalId,'Year2019.Mips134', MeasureStatusValue.GAP, "G8432");
end
