package com.ablehealth.drools.rules;

import com.ablehealth.model.Person;


rule "is-Dave-rule"
agenda-group "names-lastnames"
 when
       $p:Person( $p.name  == "Dave" )
   then
   		$p.setLastName("Smith");
        System.out.println( "Regla activada! It's Dave!!" + " " + $p.getLastName()+ " "+ drools.getRule().getName());
   end
   
   
 rule "isnt-Dave-rule"
 when
       $p:Person( $p.name  != "Dave" )
   then
   		$p.setLastName("Doe");
        System.out.println( "Regla activada! -- Isn't Dave!! :(  "  + " " + $p.getLastName()+ " " + drools.getRule().getName());
   end
   
   
 rule "last-name-rule"
 when
       $p:Person( $p.lastName  != "Doe" )
   then
        System.out.println( "Regla activada! -- Isn't Doe!! :(  "  + " " + drools.getRule().getName());
   end