package com.ablehealth;

import com.ablehealth.model.*
import com.ablehealth.payloads.*;
import com.ablehealth.results.*;

global PatientResults controlSet;

rule 'Year2019.Mipspiep1uncontrolled.Denominator'
when
    $program: Program(rules contains 'measure.Pi.2019.Mipspiep1uncontrolled')
    $encounter: Medication(
        startsDuring($program.piMeasurementPeriod),
        prescribed == true,
        controlledSubstance == false
    )
then
    insert(new EncounterDenominator($program, $encounter, 'Year2019.Mipspiep1uncontrolled'));
end

rule 'Year2019.Mipspiep1uncontrolled.Success.performance_met'
when
    EncounterDenominator($program: program, $encounter: medication, measure == 'Year2019.Mipspiep1uncontrolled')
    eval($encounter.prescriptionMethod != null && $encounter.prescriptionMethod.equals('electronic'))
then
    controlSet.addEncounterMeasureStatus($program, $encounter, 'Year2019.Mipspiep1uncontrolled', MeasureStatusValue.SUCCESS, "performance_met");
end

rule 'Year2019.Mipspiep1uncontrolled.Gap.performance_not_met'
when
    EncounterDenominator($program: program, $encounter: medication, measure == 'Year2019.Mipspiep1uncontrolled')
then
    controlSet.addEncounterMeasureStatus($program, $encounter, 'Year2019.Mipspiep1uncontrolled', MeasureStatusValue.GAP, "performance_not_met");
end
