package com.ablehealth;

import com.ablehealth.model.*
import com.ablehealth.payloads.*;
import com.ablehealth.results.*;

import java.util.Collection;

global PatientResults controlSet;
global Collection<Provider> providers;

rule 'Year2019.Stage3cpoelab.Denominator'
when
    $program: Program(rules contains 'measure.Pi.2019.Stage3cpoelab')
    $encounter: Order(
        startsDuring($program.piMeasurementPeriod),
        codeType == "CPT",
        codeValueInExclusiveRange(79999, 90000)
    )
then
    insert(new EncounterDenominator($program, $encounter, 'Year2019.Stage3cpoelab'));
end

rule 'Year2019.Stage3cpoelab.Success.performance_met'
when
    EncounterDenominator($program: program, $encounter: order, measure == 'Year2019.Stage3cpoelab')
    eval($encounter.computerizedPhysicianOrderEntry != null && $encounter.computerizedPhysicianOrderEntry == true)
then
    controlSet.addEncounterMeasureStatusesForMatchingProviders($program, $encounter, 'Year2019.Stage3cpoelab', MeasureStatusValue.SUCCESS, "performance_met", providers);
end

rule 'Year2019.Stage3cpoelab.Gap.performance_not_met'
when
    EncounterDenominator($program: program, $encounter: order, measure == 'Year2019.Stage3cpoelab')
then
    controlSet.addEncounterMeasureStatusesForMatchingProviders($program, $encounter, 'Year2019.Stage3cpoelab', MeasureStatusValue.GAP, "performance_not_met", providers);
end
