package com.ablehealth;

import com.ablehealth.model.*
import com.ablehealth.payloads.*;
import com.ablehealth.results.*;

import java.util.Collection;

global PatientResults controlSet;
global Collection<Provider> providers;

rule 'Year2019.Stage3epuncontrolled.Denominator'
when
    $program: Program(rules contains 'measure.Pi.2019.Stage3epuncontrolled')
    $encounter: Medication(
        startsDuring($program.piMeasurementPeriod),
        prescribed == true,
        controlledSubstance == false
    )
then
    insert(new EncounterDenominator($program, $encounter, 'Year2019.Stage3epuncontrolled'));
end

rule 'Year2019.Stage3epuncontrolled.Success.performance_met'
when
    EncounterDenominator($program: program, $encounter: medication, measure == 'Year2019.Stage3epuncontrolled')
    eval($encounter.prescriptionMethod != null && $encounter.prescriptionMethod.equals('electronic'))
then
    controlSet.addEncounterMeasureStatusesForMatchingProviders($program, $encounter, 'Year2019.Stage3epuncontrolled', MeasureStatusValue.SUCCESS, "performance_met", providers);
end

rule 'Year2019.Stage3epuncontrolled.Gap.performance_not_met'
when
    EncounterDenominator($program: program, $encounter: medication, measure == 'Year2019.Stage3epuncontrolled')
then
    controlSet.addEncounterMeasureStatusesForMatchingProviders($program, $encounter, 'Year2019.Stage3epuncontrolled', MeasureStatusValue.GAP, "performance_not_met", providers);
end
