package com.ablehealth;

import com.ablehealth.model.*
import com.ablehealth.payloads.*;
import com.ablehealth.results.*;

import java.util.Collection;

global PatientResults controlSet;
global Collection<Provider> providers;

rule 'Year2019.Stage3cpoemedication.Denominator'
when
    $program: Program(rules contains 'measure.Pi.2019.Stage3cpoemedication')
    $encounter: Medication(
        startsDuring($program.piMeasurementPeriod),
        prescribed == true
    )
then
    insert(new EncounterDenominator($program, $encounter, 'Year2019.Stage3cpoemedication'));
end

rule 'Year2019.Stage3cpoemedication.Success.performance_met'
when
    EncounterDenominator($program: program, $encounter: medication, measure == 'Year2019.Stage3cpoemedication')
    eval($encounter.computerizedPhysicianOrderEntry != null && $encounter.computerizedPhysicianOrderEntry == true)
then
    controlSet.addEncounterMeasureStatusesForMatchingProviders($program, $encounter, 'Year2019.Stage3cpoemedication', MeasureStatusValue.SUCCESS, "performance_met", providers);
end

rule 'Year2019.Stage3cpoemedication.Gap.performance_not_met'
when
    EncounterDenominator($program: program, $encounter: medication, measure == 'Year2019.Stage3cpoemedication')
then
    controlSet.addEncounterMeasureStatusesForMatchingProviders($program, $encounter, 'Year2019.Stage3cpoemedication', MeasureStatusValue.GAP, "performance_not_met", providers);
end

